name: Update README with Website Statuses

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    branches: ['master', 'main']

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check website status
        id: check_websites
        run: |
          echo '# Movie-Web Instances Statuses' > README.md
          while IFS= read -r site; do
            if [[ -z "$site" ]]; then
              continue
            fi
           status_code=$(curl --write-out %{http_code} --silent --output /dev/null --max-time 15 "https://$site")
            if [ $status_code -eq 200 ]; then
              echo "$site: 🟢" >> README.md
            else
              echo "$site: 🔴" >> README.md
            fi
            echo >> README.md
          done < sites.txt

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --staged --quiet || git commit -m "Update README with Movie-Web Instances Statuses"
          git push
